"use client";
import "./globals.css";
import { Poppins, Inter } from "next/font/google";
import Navbar from "./Navbar";
import { usePathname } from "next/navigation";
import { SessionProvider } from "next-auth/react";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const inter = Inter({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };
const disabledNavbar = ["/login", "/register"];

export default function RootLayout({ children }: { children: React.ReactNode }) {
    const pathname = usePathname();

    return (
        <html lang="en">
            <body className={poppins.className}>
                {/* {pathname !== "/login" && pathname !== "/register" ? <Navbar /> : ""} */}

                <SessionProvider>
                    {!disabledNavbar.includes(pathname) && <Navbar />}
                    {children}
                </SessionProvider>
            </body>
        </html>
    );
}
